name: dependencies_flutter
description: A simple and modular dependency injection system without using reflection.
version: 0.0.5
homepage: https://github.com/marcguilera/dart_dependencies_flutter
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  dependencies: ^0.0.5
  flutter:
    sdk: flutter