name: dependencies_flutter
description: A simple and modular dependency injection system for Flutter.
version: 0.1.6
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  dependencies:
    git:
      url: git://github.com/Cilestal/dependencies.dart
  flutter:
    sdk: flutter
